# Generated by Django 3.0.8 on 2020-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200709_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
