# Generated by Django 3.0.8 on 2020-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200711_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
