# Generated by Django 3.0.8 on 2020-07-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200711_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Listings'),
        ),
    ]
