# Generated by Django 3.0.8 on 2020-07-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200713_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(default='Bilge', on_delete=django.db.models.deletion.CASCADE, related_name='listowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
