# Generated by Django 3.0.8 on 2020-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200713_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
