# Generated by Django 3.0.8 on 2020-07-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200713_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='owner',
        ),
    ]
