# Generated by Django 3.0.8 on 2020-07-13 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
