# Generated by Django 3.0.8 on 2020-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], max_length=32),
        ),
    ]
