# Generated by Django 3.0.8 on 2020-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20200713_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=32),
        ),
    ]
