# Generated by Django 3.0.8 on 2020-08-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='timestamp',
        ),
    ]
