# Generated by Django 3.0.8 on 2020-08-01 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_remove_email_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
