# Generated by Django 3.0.8 on 2020-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_email_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
